name: flutter_application_5
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  http: any
  shared_preferences: ^2.0.15 # Usa una sola versión de shared_preferences
  dio: ^5.7.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  crypto: ^3.0.1
  flutter_secure_storage: ^6.1.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Aquí agregamos la sección de assets
  assets:
    - assets/img/logo.png
    - assets/img/rest.jpg
    - assets/img/logo2.png
    - assets/img/platos.jpg
